# Generated by Django 3.2.7 on 2021-09-08 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagnikapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 20, 15, 14, 116502)),
        ),
    ]
