# Generated by Django 3.2.7 on 2021-09-23 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagnikapp', '0003_auto_20210916_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CALORIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('physical_activity', models.CharField(max_length=50)),
                ('calorie', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 17, 51, 10, 573907))),
            ],
        ),
        migrations.AlterField(
            model_name='bmi',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 17, 51, 10, 573907)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 17, 51, 10, 558280)),
        ),
    ]
